---
- name: Download Miniconda installer
  become: false
  get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "/tmp/miniconda.sh"
    mode: "0755"

- name: Install Miniconda silently
  become: false
  command: "/tmp/miniconda.sh -b -u -p ~/miniconda3"
  args:
    creates: "~/miniconda3/bin/conda"

- name: Initialize Conda for Bash
  become: false
  command: "~/miniconda3/bin/conda init bash"
  changed_when: false
