---
- name: Install Neovim
  become: true
  unarchive:
    src: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
    dest: "/opt/"
    remote_src: yes
    creates: "/opt/nvim-linux-x86_64/bin/nvim"

- name: Create symlink to nvim binary
  become: true
  file:
    src: "/opt/nvim-linux-x86_64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link

- name: Ensure .config dir exists
  become: false
  file:
    path: "~/.config"
    state: directory
    mode: "0755"

- name: Symlink Neovim config
  become: false
  file:
    src: "{{ playbook_dir }}/configs/nvim"
    dest: "~/.config/nvim"
    state: link
    force: yes
